### ISSUE TITLE
Add kubevirt.io/v1 apiVersion to the webhook rules

### ISSUE THREAD

**Issue by coboluxx** [k8snetworkplumbingwg/kubemacpool#264]
**What happened**:
kubemacpool does not provide a mac to kubevirt machiens deployed with apiVersion kubevirt.io/v1

**What you expected to happen**:

mac address assigned.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new machine with with the apiVersion kubevirt.io/v1 (kubevirt v0.37.0)

**Anything else we need to know?**:

The webhook rules need an update to include v1

```yaml
rules:
  - apiGroups:
    - kubevirt.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
```
