### ISSUE TITLE
All mac addresses are got lost when vm yamls applies more the 1 time

### ISSUE THREAD

**Issue by nikita133** [K8sNetworkPlumbingWG/kubemacpool#31]
Scenario:
1)Create VM-A . 
> oc apply -f vm_a.yaml
2) Check mac addresses from spec
>oc describe vm vma | grep 'Mac '
            Mac Address:  02:83:e8:00:00:37
3) Apply again same yaml.  
>oc apply -f vm_a.yaml
4) Check MAC in vm spec. 
>oc describe vm vma | grep 'Mac '
BUG: There is no mac address.

vm yaml:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
metadata:
  name: vma        
  namespace: myproject
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
            - name: br1
              bridge: {}
        resources:
          requests:
            memory: 1G      
        cpu:
          cores: 2
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/fedora-cloud-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              runcmd:
                - sudo nmcli con mod 'Wired connection 1' ipv4.address 10.201.0.1/24
                - sudo nmcli con mod 'Wired connection 1' ipv4.method manual
                - sudo nmcli con up 'Wired connection 1'
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: br1
          name: br1
```
