### ISSUE TITLE
kubemacpool doesn't release mac addresses of removed vm's interfaces

### ISSUE THREAD

**Issue by nikita133** [K8sNetworkPlumbingWG/kubemacpool#44]
Issue: kubemacpool doesn't release mac addresses of removed vm's interfaces
Scenario:
**Create VM-a 2 interfaces + static mac on one of them:**

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
metadata:
  name: vma    
  namespace: myproject
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: br1
              bridge: {}
            - name: br2
              macAddress: 06:bb:bb:00:00:01
              bridge: {}
        resources:
          requests:
            memory: 2G      
        cpu:
          cores: 1
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/fedora-cloud-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              runcmd:
                - sudo nmcli con mod 'Wired connection 1' ipv4.address 10.201.0.1/24
                - sudo nmcli con mod 'Wired connection 1' ipv4.method manual
                - sudo nmcli con up 'Wired connection 1'
                - sudo nmcli con mod 'Wired connection 2' ipv4.address 10.202.0.1/24
                - sudo nmcli con mod 'Wired connection 2' ipv4.method manual
                - sudo nmcli con up 'Wired connection 2'
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: br1
          name: br1
        - multus:
            networkName: br1
          name: br2
```
**Remove interface with static mac from vma:**
Delete following section:
            - name: br2
              macAddress: 06:bb:bb:00:00:01
              bridge: {}
        - multus:
            networkName: br1
          name: br2
**Reapply yaml**
>oc apply -f yaml

**Create new VM-B with same static mac as was used by VM-A:**
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
metadata:
  name: vmb    
  namespace: myproject
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: br1
              bridge: {}
            - name: br2
              macAddress: 06:bb:bb:00:00:01
              bridge: {}
        resources:
          requests:
            memory: 2G      
        cpu:
          cores: 1
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/fedora-cloud-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              runcmd:
                - sudo nmcli con mod 'Wired connection 1' ipv4.address 10.201.0.1/24
                - sudo nmcli con mod 'Wired connection 1' ipv4.method manual
                - sudo nmcli con up 'Wired connection 1'
                - sudo nmcli con mod 'Wired connection 2' ipv4.address 10.202.0.1/24
                - sudo nmcli con mod 'Wired connection 2' ipv4.method manual
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: br1
          name: br1
        - multus:
            networkName: br1
          name: br2
```

**Error:**
{"level":"error","ts":1562074389.970346,"logger":"PoolManager","msg":"mac address already allocated","error":"failed to allocate requested mac address","stacktrace":"github.com/K8sNetworkPlumbingWG/kubemacpool/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/pkg/pool-manager.(*PoolManager).allocateRequestedVirtualMachineInterfaceMac\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/pkg/pool-manager/virtualmachine_pool.go:145\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/pkg/pool-manager.(*PoolManager).AllocateVirtualMachineMac\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/pkg/pool-manager/virtualmachine_pool.go:68\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/pkg/webhook/virtualmachine.(*virtualMachineAnnotator).mutateVirtualMachinesFn\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/pkg/webhook/virtualmachine/virtualmachine.go:98\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/pkg/webhook/virtualmachine.(*virtualMachineAnnotator).Handle\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/pkg/webhook/virtualmachine/virtualmachine.go:85\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).handleMutating\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:133\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:120\ngithub.com/K8sNetworkPlumbingWG/kubemacpool/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/src/github.com/K8sNetworkPlumbingWG/kubemacpool/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:93\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2361\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2741\nnet/http.initNPNRequest.ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:3291\nnet/http.Handler.ServeHTTP-fm\n\t/usr/lib/golang/src/net/http/h2_bundle.go:5592\nnet/http.(*http2serverConn).runHandler\n\t/usr/lib/golang/src/net/http/h2_bundle.go:5877"}
